spring:
  config:
    activate:
      on-profile: local
  cloud:
    vault:
      enabled: false
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5432/newsbot}
    username: ${SPRING_R2DBC_USERNAME:newsbot_run}
    password: ${SPRING_R2DBC_PASSWORD:senha123}
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:}
      chat:
        completions-path: ${OPENAI_CHAT_COMPLETIONS_PATH:/v1/chat/completions}
        base-url: ${OPENAI_BASE_URL:https://api.openai.com}

app:
  discord:
    webhook-url: ${DISCORD_WEBHOOK_URL:}

# Local overrides for any other secrets or endpoints can be provided via
# environment variables or this profile-specific file without relying on Vault.
