spring:
  config:
    activate:
      on-profile: prod
    import: vault://
  cloud:
    vault:
      enabled: true
      uri: ${SPRING_CLOUD_VAULT_URI}
      scheme: ${SPRING_CLOUD_VAULT_SCHEME:https}
      connection-timeout: ${SPRING_CLOUD_VAULT_CONNECTION_TIMEOUT:5s}
      read-timeout: ${SPRING_CLOUD_VAULT_READ_TIMEOUT:5s}
      kv:
        enabled: true
        backend: ${SPRING_CLOUD_VAULT_KV_BACKEND:secret}
        default-context: discord-news-bot
        profile-separator: /
        profiles: prod
      authentication: ${SPRING_CLOUD_VAULT_AUTHENTICATION:approle}
      app-role:
        role-id: ${SPRING_CLOUD_VAULT_APP_ROLE_ID:}
        secret-id: ${SPRING_CLOUD_VAULT_APP_ROLE_SECRET_ID:}
      token: ${SPRING_CLOUD_VAULT_TOKEN:}
      namespace: ${SPRING_CLOUD_VAULT_NAMESPACE:}
      config:
        lifecycle:
          enabled: true

